# Generated by Django 3.0.1 on 2019-12-26 21:17

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecategory',
            options={'verbose_name_plural': 'Attendance Categories'},
        ),
        migrations.AlterField(
            model_name='dailyreportitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlyreportitem',
            name='month',
            field=month.models.MonthField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='srt.Person'),
        ),
        migrations.AlterField(
            model_name='reportingassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='srt.Person'),
        ),
    ]
