# Generated by Django 3.0.1 on 2019-12-30 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingassignment',
            name='category',
        ),
        migrations.CreateModel(
            name='ReportingAssignmentAttendanceCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='srt.ReportingAssignment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srt.AttendanceCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
