# Generated by Django 3.0.1 on 2019-12-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0002_auto_20191226_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreportitem',
            old_name='month',
            new_name='year_month',
        ),
    ]
