# Generated by Django 3.0.1 on 2019-12-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('srt', '0003_auto_20191226_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_srt.dailyreportitem_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='monthlyreportitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_srt.monthlyreportitem_set+', to='contenttypes.ContentType'),
        ),
    ]
