# Generated by Django 3.0.1 on 2019-12-26 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('srt', '0004_auto_20191226_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='count',
        ),
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='dailyreportitem',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='count',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='monthlyreportitem',
            name='uuid',
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srt.AttendanceCategory')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_srt.reportitem_set+', to='contenttypes.ContentType')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srt.Report')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srt.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailyreportitem',
            name='reportitem_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='srt.ReportItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreportitem',
            name='reportitem_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='srt.ReportItem'),
            preserve_default=False,
        ),
    ]
