image: google/cloud-sdk:alpine

stages:
  - build
  - deploy

build:
  image: node:alpine
  stage: build
  script:
    - cd react-app
    - apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
    - npm install
    - npm run build --prod || cat /root/.npm/_logs/*.log
  artifacts:
    untracked: true

deploy_production:
  stage: deploy
  environment: Production
  dependencies: 
    - build
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

deploy_staging:
  stage: deploy
  environment: Staging
  dependencies: 
    - build
  only:
  - stage
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app_stage.yaml
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json