image: google/cloud-sdk:alpine

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules

build:
  stage: build
  script:
    - cd react-app
    - npm install
    - npm run-script build

deploy_production:
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml

deploy_staging:
  stage: deploy
  environment: Staging
  only:
  - stage
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml

after_script:
- rm /tmp/$CI_PIPELINE_ID.json